[platformio]
default_envs = emulator

[env]
lib_deps =
    lvgl/lvgl@^9.5.0
    bblanchon/ArduinoJson@^7.0.0
    knolleary/PubSubClient@^2.8
    https://github.com/me-processware/JC3248W535-Driver.git
    tamctec/TAMC_GT911@^1.0.2
    bodmer/TJpg_Decoder@^1.1.0

[env:emulator]
platform = native
build_flags = -std=c++14 -I include
lib_ldf_mode = chain
extra_scripts = post:scripts/install_lv_drivers.py

[env:esp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = dio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
build_flags =
    -I include
    -Wall
    -DLV_USE_SDL=0
    -DLV_USE_GIF=1
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_CACHE_WORKAROUND
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -mfix-esp32-psram-cache-issue
    -DMQTT_MAX_PACKET_SIZE=2048
board_build.partitions = default_16MB.csv